site_name: Tsukimakura's notebook
site_description: 计算机科学、信息安全与基础学科的学习笔记
repo_url: https://github.com/Tsukimakura/My-notebook
repo_name: Tsukimakura/My-notebook
edit_uri: edit/main/docs/
theme:
  name: material

  icon:
    logo: material/github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      icon: material/brightness-7 
      name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      icon: material/brightness-4
      name: Switch to light mode

  features:
      - navigation.top # 返回顶部按钮
      - navigation.tabs # 顶部分类标签
      - navigation.sections
      - navigation.indexes
      - navigation.footer
      - search.highlight # 搜索结果高亮显示
      - search.share
      - content.action.edit
      - content.action.view
      - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - assets/vendor/katex/katex.min.js
  - assets/vendor/katex/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - assets/vendor/katex/katex.min.css

copyright: Copyright © 2025 Tsukimakura
